### ISSUE TITLE
Error when no seasonal component

### ISSUE THREAD

**Issue by AQLT** [rjdverse/rjd3tramoseats#45]
It seems that some specifications produces an error which do not occurs in v2 or in the interface. For thoses series the workspaces cannot be imported with `rjd3workspace`. 
I've created here a dummy example but the error is not necessary linked to a warning in the decomposition model. My understanding is that it occurs when there is no seasonal component (s=0 or s=1).

``` r
y <- ts(c(85, 125, 94, 168, 172, 127, 180, 87, 137, 106, 141, 
135, 110, 123, 129, 138, 156, 88, 99, 158, 136, 98, 140, 98, 
126, 136, 124, 115, 140, 122, 204, 191, 218, 115, 183, 188, 159, 
227, 100, 128, 98, 182, 169, 123, 155, 174, 175, 145, 141, 188, 
218, 170, 105, 168, 114, 118, 137, 112, 171, 143, 135),
start = 2000, frequency = 4)
mod <- RJDemetra::tramoseats(y)
#> Warning in tramoseatsJavaResults(jrslt = jrslt, spec = jrspec, userdefined =
#> userdefined): [decomposition.Model decomposition: Parameters cut off]
rjd3tramoseats::tramoseats(y)
#> Error in .jcall("jdplus/tramoseats/base/r/TramoSeats", "[B", "toBuffer", : java.lang.NullPointerException: Cannot invoke "jdplus.toolkit.base.api.timeseries.TsData.getStart()" because "s" is null
```

**Comment by palatej** [comment]
Hi Alain,
Thanks for your remark.
I also saw the problem. It is corrected, but I still have to push the new java libraries. Planned for the next future
